### ISSUE TITLE
add min-global-align to the target specifications

### ISSUE THREAD

**Issue by japaric** [japaric/nvptx#10]
once rust-lang/rust#44440 is in nightly

**Comment by cuviper** [comment]
FWIW, Clang just copies the host value, as it apparently does for many properties:
https://github.com/llvm-mirror/clang/blob/aae8a30c39b60e5ef14e565557b7fc398112d1e5/lib/Basic/Targets/NVPTX.cpp#L101

**Comment by japaric** [comment]
OK, that sounds like we won't actually need this until someone needs to use CUDA with either a SystemZ processor or a Lanai processor. We don't support the latter so I'm going to defer this until someone comes up with the SystemZ+CUDA use case.

Thanks for the info, @cuviper.
